#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "koffan"
name = "Koffan"
description.en = "Groceries list for families and shared households."
description.fr = "Liste de courses pour familles et foyers partagés."

version = "2.12.2~ynh1"

maintainers = ["guillaumelegoc"]

[upstream]
license = "MIT"
code = "https://github.com/PanSalut/Koffan"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    help.en = "This password will be used by all Koffan users"
    type = "password"

    [install.language]
    ask.en = "Choose the app language"
    help.en = "Choose from pl, en, de, es, fr, pt, uk, no, lt, el, sk, ru"
    type = "string"
    default="en"

[resources]
    [resources.sources]
        [resources.sources.main]
        in_subdir = true
        url = "https://github.com/PanSalut/Koffan/archive/refs/tags/v2.12.2.tar.gz"
        sha256 = "988235a7c665dfee158ef46d8be1b512ff679ddde60608759200084e2bde1c63"
        autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.go]
    version = "1.21"